### ISSUE TITLE
For real blur dataset, how can you get the poses during the exposure?

### ISSUE THREAD

**Issue by chenkang455** [iCVTEAM/E2NeRF#1]
Hi! Thanks for your great work! I have a small concern regarding the pose estimation module. In the paper, it was mentioned that the EDI  model was used to deblur the images before feeding them into COLMAP for pose estimation. However, it seems that this process is only capable of deriving the pose of the central moment during the exposure (as stated in the paper). What about the other poses during the exposure?

**Comment by 171164558** [comment]
Hi,  I have updated the EDI code. With this code you can general b+1 sharp images for each view during the exposure, and with COLMAP, you can obtain the b+1 poses.
